import{storage}from'./storage.js';import{migrate}from'./data.js';import{icons,toast}from'./ui.js';import{renderDashboard,todayName}from'./dashboard.js';import{renderExercises,bindExercises}from'./exercises.js';import{renderSchedule,bindSchedule}from'./schedule.js';import{createWorkout,renderWorkout,bindWorkout}from'./workouts.js';import{renderHistory,bindHistory}from'./history.js';import{renderAccount,bindAccount}from'./account.js';import{cloudConfigured,initCloud,currentUser,signUp,signIn,signOut,loadCloudState,saveCloudState,queueCloudSave,onSyncStatus}from'./cloud.js';
let state=migrate(storage.load()),user=null,sync={value:'local',message:'Saved on this device'};const app=document.querySelector('#app');const routes=[['dashboard','Dashboard'],['schedule','Schedule'],['exercises','Exercises'],['history','History'],['account','Account']];
function save(){storage.save(state);queueCloudSave(state)}function route(){return location.hash.slice(1)||'dashboard'}function navigate(to){location.hash=to;if(route()===to)render()}
function nav(){const html=routes.map(([id,label])=>`<a href="#${id}" class="nav-link ${route()===id?'active':''}"><span class="nav-icon">${icons[id]||'A'}</span><span>${label}</span></a>`).join('');document.querySelector('#desktop-nav').innerHTML=html;document.querySelector('#mobile-nav').innerHTML=html;}
function render(){nav();const r=route();if(r==='dashboard'){app.innerHTML=renderDashboard(state);const b=document.querySelector('#start-workout');if(b)b.onclick=()=>{if(!state.activeWorkout){const day=todayName(),plan=state.schedule[day]||state.schedule.Monday;state.activeWorkout=createWorkout(day,plan,state);save();toast('Workout started');}navigate('workout');};}else if(r==='schedule'){app.innerHTML=renderSchedule(state);bindSchedule(state,save,render);}else if(r==='exercises'){app.innerHTML=renderExercises(state,save,render);bindExercises(state,save,render);}else if(r==='history'){app.innerHTML=renderHistory(state);bindHistory(state);}else if(r==='workout'){app.innerHTML=renderWorkout(state);bindWorkout(state,save,render,navigate);}else if(r==='account'){app.innerHTML=renderAccount({configured:cloudConfigured(),user,sync});bindAccount({signin:authenticateSignIn,signup:authenticateSignUp,sync:syncNow,signout:logout});}else navigate('dashboard');window.scrollTo(0,0);app.focus({preventScroll:true});}
async function restoreOrBackUp(){const remote=await loadCloudState(),localUpdated=storage.updatedAt();if(!remote){await saveCloudState(state);toast('Local progress backed up');return;}if(localUpdated&&new Date(localUpdated)>new Date(remote.updated_at)){await saveCloudState(state);toast('Newer local progress backed up');return;}state=migrate(remote.state);storage.save(state,remote.updated_at);toast('Cloud backup restored');}
async function authenticateSignIn(email,password){const result=await signIn(email,password);user=result.user;await restoreOrBackUp();render();}
async function authenticateSignUp(email,password){const result=await signUp(email,password);user=result.session?.user||null;if(user){await restoreOrBackUp();toast('Account created');}else toast('Check your email to confirm your account');render();}
async function syncNow(){try{await saveCloudState(state);toast('Backup is up to date');render();}catch(error){toast(error.message);}}
async function logout(){await signOut();user=null;sync={value:'local',message:'Saved on this device'};toast('Signed out');render();}
async function boot(){onSyncStatus(next=>{sync=next;if(route()==='account')render();});initCloud();if(cloudConfigured()){try{user=await currentUser();if(user)await restoreOrBackUp();}catch(error){sync={value:'error',message:error.message};}}if(!storage.load())storage.save(state);render();}
window.addEventListener('hashchange',render);boot();