export const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const ex=(id,name,category,type='reps',difficulty='Intermediate',variation='')=>({id,name,category,type,variation,difficulty,isCustom:false,description:`${difficulty} ${category.toLowerCase()} movement.`,muscles:[category]});
export const starterExercises=[
...['Pull-Up','Archer Pull-Up','Chin-Up','Wide Pull-Up','High Pull-Up','Muscle-Up'].map((n,i)=>ex(`pull-${i}`,n,'Pull','reps',i?'Intermediate':'Beginner')),ex('weighted-pullup','Weighted Pull-Up','Pull','weighted_reps','Advanced'),
...['Push-Up','Diamond Push-Up','Archer Push-Up','Decline Push-Up','Clap Push-Up','One-Arm Push-Up','Hindu Push-Up','Russian Push-Up','Russian Dip','Impossible Dip','Straight Bar Dip','Ring Dip'].map((n,i)=>ex(`push-${i}`,n,'Push','reps',i<2?'Beginner':i<6?'Intermediate':'Advanced')),ex('weighted-dip','Weighted Dip','Push','weighted_reps','Advanced'),
ex('handstand-hold','Handstand Hold','Handstand','hold'),...['Handstand Push-Up','Wall Handstand Push-Up','Pike Push-Up','90-Degree Handstand Push-Up'].map((n,i)=>ex(`handstand-${i}`,n,'Handstand','reps',i===2?'Intermediate':'Advanced')),
...['Tuck','Advanced Tuck','Straddle','Full'].map((v,i)=>ex(`planche-hold-${i}`,`Planche Hold — ${v}`,'Planche','hold','Advanced',v)),...['Tuck','Advanced Tuck','Straddle','Full'].map((v,i)=>ex(`planche-pushup-${i}`,`Planche Push-Up — ${v}`,'Planche','reps','Advanced',v)),...['Tuck','Straddle','Full'].map((v,i)=>ex(`planche-press-${i}`,`Planche Press — ${v}`,'Planche','reps','Advanced',v)),...['Planche Lean','Pseudo Planche Push-Up','Hollow Body Dumbbell Raises','Negative Planche Press','Negative Planche Push-Up'].map((n,i)=>ex(`planche-other-${i}`,n,'Planche',n==='Planche Lean'?'hold':'reps','Advanced')),
...['Hold','Raises','Pulls'].flatMap((move,mi)=>['Tuck','Advanced Tuck','Half Lay','Straddle','Full'].map((v,i)=>ex(`front-lever-${mi}-${i}`,`Front Lever ${move} — ${v}`,'Front Lever',move==='Hold'?'hold':'reps','Advanced',v))),
ex('l-sit','L-Sit','Core','hold'),ex('leg-raises','Leg Raises','Core'),ex('hollow-hold','Hollow Body Hold','Core','hold'),ex('plank','Plank','Core','hold','Beginner'),ex('side-plank','Side Plank','Core','hold','Beginner'),ex('reverse-plank','Reverse Plank','Core','hold','Beginner'),...['Pistol Squat','Bulgarian Squat','Normal Squat','Walking Lunges','Calf Raises','Single-Leg Romanian Deadlift'].map((n,i)=>ex(`legs-${i}`,n,'Legs','reps',i===2?'Beginner':'Intermediate')),ex('wall-sit','Wall Sit','Legs','hold','Beginner')];
const item=(exerciseId,sets,target,weight=0)=>({exerciseId,sets,target,weight,order:0});
export function initialState(){return{exercises:starterExercises,schedule:{Monday:{name:'Push',rest:false,exercises:[item('push-0',4,12),item('push-8',4,8),item('handstand-2',3,10)]},Tuesday:{name:'Pull',rest:false,exercises:[item('pull-0',4,8),item('pull-2',3,10),item('front-lever-0-0',3,15)]},Wednesday:{name:'Legs',rest:false,exercises:[item('legs-2',4,15),item('legs-1',3,10),item('wall-sit',3,40)]},Thursday:{name:'Rest',rest:true,exercises:[]},Friday:{name:'Push',rest:false,exercises:[item('handstand-0',4,5),item('weighted-dip',4,8,10),item('planche-hold-0',4,12)]},Saturday:{name:'Pull',rest:false,exercises:[item('weighted-pullup',4,6,10),item('pull-5',3,4),item('front-lever-1-0',3,8)]},Sunday:{name:'Rest',rest:true,exercises:[]}},workouts:[],activeWorkout:null,settings:{defaultRest:90}}}
export function migrate(saved){const fresh=initialState();if(!saved)return fresh;const savedOnly=(saved.exercises||[]).filter(old=>!starterExercises.some(exercise=>exercise.id===old.id));return{...fresh,...saved,exercises:[...starterExercises,...savedOnly],settings:{...fresh.settings,...saved.settings}};}
